# Generated by Django 3.2.5 on 2022-01-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_database', '0002_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
